export enum Specialty {
    Allergology = 'Allergology',
    Anesthesiology = 'Anesthesiology',
    Cardiology = 'Cardiology',
    Dermatology = 'Dermatology',
    Endocrinology = 'Endocrinology',
    Gastroenterology = 'Gastroenterology',
    Geriatrics = 'Geriatrics',
    Gynecology = 'Gynecology',
    Hematology = 'Hematology',
    Infectology = 'Infectology',
    InternalMedicine = 'Internal Medicine',
    Nephrology = 'Nephrology',
    Pulmonology = 'Pulmonology',
    Neurology = 'Neurology',
    Nutrition = 'Nutrition',
    Dentistry = 'Dentistry',
    Ophthalmology = 'Ophthalmology',
    Oncology = 'Oncology',
    Orthopedics = 'Orthopedics',
    Otolaryngology = 'Otolaryngology',
    Pediatrics = 'Pediatrics',
    Psychology = 'Psychology',
    Psychiatry = 'Psychiatry',
    Radiology = 'Radiology',
    Rheumatology = 'Rheumatology',
    Traumatology = 'Traumatology',
    Urology = 'Urology'
  }
  